-- 최고 마지막 구하기(ITEM_TREE - PARENT_ITEM_ID의 값에 해당하지 않는 것들 구하기!)
# WITH ITEM_INFO_ALL AS (
#     SELECT II.ITEM_ID AS ID, II.ITEM_NAME, II.RARITY
#     FROM ITEM_INFO II, ITEM_TREE IT
#     WHERE II.ITEM_ID NOT IN IT.PARENT_ITEM_ID
# )

# SELECT ITEM_ID AS ID, ITEM_NAME, RARITY
# FROM ITEM_INFO_ALL
# ORDER BY ITEM_ID DESC

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID 
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC