SELECT P.ID, IFNULL(COUNT(C.ID), 0) AS CHILD_COUNT
# FROM ECOLI_DATA P, ECOLI_DATA C
# WHERE C.PARENT_ID = P.ID
FROM ECOLI_DATA P
LEFT JOIN ECOLI_DATA C ON C.PARENT_ID = P.ID
GROUP BY P.ID
ORDER BY P.ID