-- 조건 : 1) 자동차 종류(세단, SUV), 2) 대여 가능일(2022-11-01 ~ 2022-11-30), 3) 최종 대여금액(50만<=X<200만)=> 30일 이상의 할인율 찾아서 곱하기
SELECT DISTINCT COM.CAR_ID, 
    COM.CAR_TYPE, 
    COM.DAILY_FEE*30*(1-DIS.DISCOUNT_RATE*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR COM
    JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상'
            AND CAR_TYPE IN ('SUV', '세단')
    ) DIS
    ON COM.CAR_TYPE = DIS.CAR_TYPE
WHERE NOT EXISTS (
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
        WHERE (START_DATE <= DATE '2022-11-01'
            AND END_DATE >= DATE '2022-11-01')
            AND COM.CAR_ID = HIS.CAR_ID
    )
    AND COM.DAILY_FEE*30*(1-DIS.DISCOUNT_RATE*0.01) >= 500000
    AND COM.DAILY_FEE*30*(1-DIS.DISCOUNT_RATE*0.01) < 2000000
ORDER BY FEE DESC, COM.CAR_TYPE, COM.CAR_ID DESC