SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN
(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    -- 이름이 다르면 나오지 않는다!
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
-- GROUP BY FOOD_TYPE
-- 서브쿼리 안에서 해줬으니까 할 필요 없다!
ORDER BY FOOD_TYPE DESC