# 대장균 개체 크기 내림차순으로 정렬하여 4등분하기(CTE 사용)
WITH COLONY_CTE AS (
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS CHECK_COLONY
    FROM ECOLI_DATA)

# 만든 CTE 사용하여 등급별 이름부여(CASE 사용)
SELECT ID,
    CASE CHECK_COLONY
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM COLONY_CTE
ORDER BY ID