-- 중성화X -> 중성화O인 동물 ID, 종, 이름
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS
    JOIN (
        SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
        FROM ANIMAL_OUTS
        WHERE SEX_UPON_OUTCOME LIKE 'Spayed%'
            OR SEX_UPON_OUTCOME LIKE 'Neutered%' 
    ) OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
ORDER BY INS.ANIMAL_ID

# SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
# FROM ANIMAL_OUTS
# WHERE SEX_UPON_INTAKE LIKE 'Spayed%' OR 'Neutered%'
# ORDER BY ANIMAL_ID