SELECT EXTRACT(YEAR FROM TRUNC(SALES_DATE, 'YYYY')) AS YEAR
    , EXTRACT(MONTH FROM TRUNC(SALES_DATE, 'MM')) AS MONTH
    , UI.GENDER AS GENDER
    , COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS, USER_INFO UI
WHERE OS.USER_ID = UI.USER_ID
    AND UI.GENDER IS NOT NULL
GROUP BY TRUNC(SALES_DATE, 'YYYY'), TRUNC(SALES_DATE, 'MM'), UI.GENDER
ORDER BY TRUNC(SALES_DATE, 'YYYY'), TRUNC(SALES_DATE, 'MM'), UI.GENDER