-- ALTER TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY ADD RENT_TYPE VARCHAR(7)

SELECT HISTORY_ID, 
    CAR_ID, 
    TO_CHAR(START_DATE,'YYYY-MM-DD') AS START_DATE, 
    TO_CHAR(END_DATE,'YYYY-MM-DD') AS END_DATE,
    CASE 
        -- WHEN (END_DATE - START_DATE) < 30 THEN '단기 대여'
        WHEN (END_DATE - START_DATE + 1) >= 30 THEN '장기 대여'
        ELSE '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE '2022-09-01' AND DATE '2022-09-30'
ORDER BY HISTORY_ID DESC