-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
# WHERE IFNULL(FREEZER_YN, 'N')
# IFNULL은 SELECT문에 사용!
# IFNULL(A, B) => A가 NULL이면 B를 적용 
ORDER BY WAREHOUSE_ID