-- 1) 2021에 가입한 회원수 구하기 => MEMBERS
WITH MEMBERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = '2021'
),
-- 2) 1)의 회원들 중 ONLINE_SALE에 있는 회원 목록 뽑기 => BUYER_MEMBERS
 BUYER_MEMBERS AS (
    SELECT OS.USER_ID, OS.SALES_DATE
    FROM MEMBERS M, ONLINE_SALE OS
    WHERE M.USER_ID = OS.USER_ID
)
-- 3) 2)에서 SALES_DATE를 기준으로 년/월 분리하기
-- 4) 3)에서 동일년월이면 USER_ID로 그룹화하기
-- 5) 1)과 2) 나눈 후 소수 둘째자리에서 반올림하기
-- 6) 년/월 오름차순 설정하기
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM MEMBERS), 1) AS PUCHASED_RATIO
FROM BUYER_MEMBERS
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR, MONTH