WITH RECURSIVE ALL_ECOLI AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, AE.GENERATION+1
    FROM ECOLI_DATA ED
        JOIN ALL_ECOLI AE
        ON ED.PARENT_ID = AE.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM ALL_ECOLI
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ALL_ECOLI
    WHERE PARENT_ID IS NOT NULL
    )
GROUP BY GENERATION
# ORDER BY GENERATION