-- 코드를 입력하세요
# SELECT CAR_ID, START_DATE, END_DATE,
#     IF (START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16', '대여중', '대여 가능') 
#     AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# # GROUP BY CAR_ID
# ORDER BY CAR_ID DESC

SELECT
  CAR_ID,
  CASE
    WHEN MIN(ABS(DATEDIFF(LEAST('2022-10-16', END_DATE), GREATEST('2022-10-16', START_DATE)))) = 0 THEN '대여중'
    ELSE '대여 가능'
  END AS AVAILABILITY
FROM
  CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
  CAR_ID
ORDER BY
  CAR_ID DESC;
