-- 코드를 입력하세요
SELECT CAR_ID, 
    # IF (START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16', '대여중', '대여 가능')
    # AS AVAILABILITY
    MAX(CASE
    WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
    ELSE '대여 가능'
    END) AS AVAILABILITY
# CASE
# WHEN 조건 THEN 값
# WHEN 조건 THEN 값
# ELSE 값
# END AS 새로운 테이블 명
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

# 아래는 GPT 풀이
# SELECT
#   CAR_ID,
#   CASE
#     WHEN MIN(ABS(DATEDIFF(LEAST('2022-10-16', END_DATE), GREATEST('2022-10-16', START_DATE)))) = 0 THEN '대여중'
#     ELSE '대여 가능'
#   END AS AVAILABILITY
# FROM
#   CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY
#   CAR_ID
# ORDER BY
#   CAR_ID DESC;