SELECT CAR_ID,
    MAX(CASE
        WHEN TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
        THEN '대여중'
        ELSE '대여 가능'
    END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH1
-- WHERE (CAR_ID, START_DATE, END_DATE) IN (
--     SELECT CAR_ID, MAX(START_DATE), MAX(END_DATE)
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH2
--     WHERE CH1.CAR_ID = CH2.CAR_ID
--     GROUP BY CAR_ID
--     )
GROUP BY CAR_ID
ORDER BY CAR_ID DESC