WITH
-- FP테이블에서 식품 ID랑 이름, 가격 빼오기
    FOOD_PRICE AS (
        SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
        FROM FOOD_PRODUCT),
-- FO테이블에서 제품(식품) ID랑 주문량, 생산일자 빼오기
    FOOD_AMOUT AS (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
        FROM FOOD_ORDER
        WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
        GROUP BY PRODUCT_ID)

SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FM.AMOUNT*FP.PRICE AS TOTAL_SALES
FROM FOOD_PRICE FP, FOOD_AMOUT FM
WHERE FP.PRODUCT_ID = FM.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID