-- 몇 시에 입양이 가장 활발하게 일어나는지 확인 => 모든 시간대(0~23)별로 입양 건 수 조회
-- WITH RECURSIVE HOURS AS (
--     SELECT 0 AS HOUR
--     UNION
--     SELECT HOUR + 1
--     FROM HOURS
--     WHERE HOUR < 23
-- )
WITH HOURS AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT H.HOUR AS HOUR, NVL(COUNT(A.ANIMAL_ID),0) AS COUNT
FROM ANIMAL_OUTS A
    RIGHT JOIN HOURS H
    ON TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR
