SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (
    SELECT S.CODE
    FROM SKILLCODES S
    WHERE (D.SKILL_CODE & S.CODE) = S.CODE
        AND S.CATEGORY = 'Front End'
    )
ORDER BY D.ID