# SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
# FROM ITEM_INFO AS INFO
# WHERE INFO.ITEM_ID IN 
#     (SELECT PARENT_ITEM_ID
#     FROM ITEM_INFO AS INFO
#         JOIN ITEM_TREE AS TREE
#         ON INFO.ITEM_ID = TREE.ITEM_ID
#     WHERE INFO.RARITY = 'RARE')
# ORDER BY INFO.ITEM_ID DESC

# 현제 풀이
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO A
  INNER JOIN ITEM_TREE B 
  ON A.ITEM_ID = B.PARENT_ITEM_ID
  INNER JOIN ITEM_INFO C 
  ON B.ITEM_ID = C.ITEM_ID
WHERE A.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC