-- -- 2022.08~2022.10 동안 월별 자동차 ID별 총 대여 횟수
-- SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,
--     CAR_ID,
--     COUNT(CAR_ID) AS RECORDS
-- -- 근데 만약 기간이 겹치면 그것도 포함해줘야하는 거 아닌지..?
-- -- 예를 들면, 8월 대여 10월 반납이면 9월에도 대여 횟수에 카운트 되어야하는데, START_DATE 기준이면 포함 못시키는 거 아닌지? 대여한 기준만 체크되는 거 아닌지..??
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE CAR_ID IN
-- -- 대여 시작일을 기준으로 2022.08~2022.10 동안 총 대여 횟수가 5회 이상인 자동차들
-- (
--     SELECT CAR_ID
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--     WHERE START_DATE > TO_DATE('2022-07', 'YYYY-MM')
--         AND END_DATE < TO_DATE('2022-11', 'YYYY-MM')
--     GROUP BY CAR_ID
--     HAVING COUNT(CAR_ID) >= 5
-- ) AND START_DATE > TO_DATE('2022-07', 'YYYY-MM')
--   AND END_DATE < TO_DATE('2022-11', 'YYYY-MM')
-- GROUP BY EXTRACT(MONTH FROM START_DATE),
--     CAR_ID
-- HAVING COUNT(CAR_ID) > 0
-- ORDER BY MONTH, CAR_ID DESC

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
     , CAR_ID
     , COUNT(HISTORY_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
   AND CAR_ID IN (
                  SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
                   GROUP BY CAR_ID HAVING COUNT(HISTORY_ID) >= 5
                 )
 GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
 ORDER BY MONTH, CAR_ID DESC