-- 2022.08~2022.10 동안 월별 자동차 ID별 총 대여 횟수
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,
    CAR_ID,
    COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
-- 대여 시작일을 기준으로 2022.08~2022.10 동안 총 대여 횟수가 5회 이상인 자동차들
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) AND TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
    -- AND START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
    -- AND END_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
GROUP BY EXTRACT(MONTH FROM START_DATE),
    CAR_ID
HAVING COUNT(CAR_ID) > 0
ORDER BY MONTH, CAR_ID DESC