SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    (MAX_SOC_OF_YEAR.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, 
    ED.ID
-- 분화된 연도, 분화된 연도별 대장균 크기 편차(가장 큰 대장균-각 대장균 크기), 대장균 개체 ID
FROM ECOLI_DATA AS ED,
    (
     -- 분화된 연도별 가장 큰 대장균 구하기
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS MAX_SOC_OF_YEAR
WHERE YEAR(ED.DIFFERENTIATION_DATE) = MAX_SOC_OF_YEAR.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC