-- 코드를 작성해주세요
SELECT DISTINCT ID, FISH_NAME, LENGTH
FROM (
    SELECT FI.ID,
        FI.LENGTH,
        FNI.FISH_NAME,
        (RANK() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC)) AS MAX_FISH
    FROM FISH_INFO FI
        JOIN FISH_NAME_INFO FNI
        ON FI.FISH_TYPE = FNI.FISH_TYPE
) AS FISH_ALL
WHERE MAX_FISH=1
ORDER BY ID
-- 종류별로 가장 큰 물고기 찾기