SELECT FI.ID, FNI.FISH_NAME, FL.LENGTH
FROM (
        SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) AS FL
    JOIN FISH_INFO FI
    ON FI.FISH_TYPE = FL.FISH_TYPE AND FI.LENGTH = FL.LENGTH
    JOIN FISH_NAME_INFO FNI
    ON FL.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID