--  2022년도 한해 평가 점수(상하반기 점수 합)가 가장 높은 사원의 점수(SCORE), 사번, 성명, 직책, 이메일
WITH EMP_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
)

SELECT
    ES.SCORE AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM
    HR_EMPLOYEES AS HE
    JOIN EMP_SCORE AS ES
    ON HE.EMP_NO = ES.EMP_NO
ORDER BY SCORE DESC
LIMIT 1