-- 부서ID, 영문부서명, 부서별 평균 연봉(AVG_SAL, 소수 첫째자리에서 반올림)
SELECT HRD.DEPT_ID, HRD.DEPT_NAME_EN, HRE.AVG_SAL
FROM HR_DEPARTMENT HRD
    JOIN (
        SELECT DEPT_ID, ROUND(AVG(SAL),0) AVG_SAL 
        FROM HR_EMPLOYEES 
        GROUP BY DEPT_ID
    ) HRE
    ON HRD.DEPT_ID = HRE.DEPT_ID
ORDER BY AVG_SAL DESC