-- 부서ID, 영문부서명, 부서별 평균 연봉(AVG_SAL, 소수 첫째자리에서 반올림)
SELECT HRD.DEPT_ID, HRD.DEPT_NAME_EN, ROUND(AVG(HRE.SAL),0) AVG_SAL
FROM HR_DEPARTMENT HRD
    JOIN HR_EMPLOYEES HRE
    ON HRD.DEPT_ID = HRE.DEPT_ID
GROUP BY HRD.DEPT_ID, HRD.DEPT_NAME_EN
ORDER BY AVG_SAL DESC