-- 지금 이상태로 돌리면 not a GROUP BY expression 이슈 발생
-- GROUP BY에 안적힌 컬럼은 찾을 수 없다!
-- SELECT CATEGORY, MAX(PRICE) AS PRICE, PRODUCT_NAME
-- FROM FOOD_PRODUCT
-- GROUP BY CATEGORY
-- HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
-- ORDER BY PRICE DESC

-- 그룹별로 묶은 상태에서 가장 큰 가격을 가진 셀 찾기
WITH MAX_PRICE AS(
SELECT CATEGORY, MAX(PRICE) AS PRICE
-- , PRODUCT_NAME
FROM FOOD_PRODUCT
GROUP BY CATEGORY
HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
-- ORDER BY PRICE DESC
)
-- 그리고 내부조인
SELECT FM.CATEGORY, FM.PRICE, FM.PRODUCT_NAME
FROM FOOD_PRODUCT FM
    JOIN MAX_PRICE MP
    ON FM.CATEGORY = MP.CATEGORY
        AND FM.PRICE = MP.PRICE
ORDER BY PRICE DESC